---
- name: Configurar servidor web
  hosts: web
  become: yes
  tasks:
    - name: Instalar Apache
      apt:
        name: apache2
        state: present

    - name: Iniciar el servicio Apache
      service:
        name: apache2
        state: started

    - name: Copiar archivo HTML al directorio de Apache
      copy:
        src: index.html
        dest: /var/www/html/index.html
